[package]
name = "minhook_rs"
version = "0.1.0"
authors = ["ryoha000 <48485650+ryoha000@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
